import turtle

screen = turtle.Screen()
screen.screensize(canvwidth=500, canvheight=500)
t = turtle.Turtle()
t.speed(0)
t.hideturtle()


#circle
t.penup()
t.goto(0, -100)
t.pendown()
t.pencolor('blue')
t.fillcolor('blue')
t.begin_fill()
t.circle(75)
t.end_fill()

t.penup()
t.goto(0, -100)
t.pendown()
t.pencolor('black')
t.fillcolor('black')
t.begin_fill()
t.circle(50)
t.end_fill()

#intro screen

t.penup()
t.goto(150,-50)
t.pendown()
screen.addshape('15.gif')
t.shape('15.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-150,-200)
t.pendown()
screen.addshape('dec.gif')
t.shape('dec.gif')
t.stamp()
t.shape('classic')

t.pencolor('white')
screen.bgcolor('black')
t.penup()
t.goto(0, 300)
t.pendown()
t.write('My name is Ethan and I am 15' ,font=('arial',30,"bold"),align="center")
t.penup()
t.goto(0, 200)
t.pendown()
t.write('My Birthday is December 27th ' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(0, -350)
t.pendown()
t.write('NEXT' ,font=('arial',30,"bold"),align="center")

round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor('blue')

#screen2
t.penup()
t.goto(-56, -100)
t.pendown()
t.pencolor('Green')
t.fillcolor('Green')
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()


t.pencolor('Black')
t.penup()
t.goto(0, 300)
t.pendown()
t.write('My Favorite Foods Are.' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(150,-50)
t.pendown()
screen.addshape('Brisket.gif')
t.shape('Brisket.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-150,-50)
t.pendown()
screen.addshape('Fries.gif')
t.shape('Fries.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(0, 150)
t.pendown()
t.write(': French Fries ' ,font=('arial',30,"bold"),align="center")
t.penup()
t.goto(0, 100)
t.pendown()
t.write(': Brisket ' ,font=('arial',30,"bold"),align="center")
t.penup()
t.goto(0, 50)
t.pendown()
t.write(': Ice Cream ' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(0, -300)
t.pendown()
t.write('NEXT' ,font=('arial',30,"bold"),align="center")

round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor('green')

#screen3
t.penup()
t.goto(70,-100 )
t.pendown()
t.setheading(135)
t.pencolor('orange')
t.fillcolor('orange')
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()

t.penup()
t.goto(-150,-150)
t.pendown()
screen.addshape('bike.gif')
t.shape('bike.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-150,0)
t.pendown()
screen.addshape('sleep.gif')
t.shape('sleep.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(150,-150)
t.pendown()
screen.addshape('swim.gif')
t.shape('swim.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(150,0)
t.pendown()
screen.addshape('eat.gif')
t.shape('eat.gif')
t.stamp()
t.shape('classic')

t.pencolor('Black')
t.penup()
t.goto(0, 300)
t.pendown()
t.write('My Hobbies Are.' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(0, 150)
t.pendown()
t.write(': Biking ' ,font=('arial',30,"bold"),align="center")
t.penup()
t.goto(0, 100)
t.pendown()
t.write(': Sleeping ' ,font=('arial',30,"bold"),align="center")
t.penup()
t.goto(0, 50)
t.pendown()
t.write(': Swimming ' ,font=('arial',30,"bold"),align="center")
t.penup()
t.goto(0, 0)
t.pendown()
t.write(': Eating ' ,font=('arial',30,"bold"),align="center")


t.penup()
t.goto(0, -300)
t.pendown()
t.write('NEXT' ,font=('arial',30,"bold"),align="center")

round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor('Orange')

#screen4
t.pencolor('red')
t.fillcolor('red')
t.begin_fill()
t.penup()
t.goto(0,-150)
t.pendown()
t.forward(150)
t.left(90)
t.forward(100)
t.left(90)
t.forward(150)
t.left(90)
t.forward(100)
t.left(90)
t.end_fill()

t.penup()
t.goto(200,0)
t.pendown()
screen.addshape('spr.gif')
t.shape('spr.gif')
t.stamp()
t.shape('classic')

t.pencolor('Black')
t.penup()
t.goto(0, 300)
t.pendown()
t.write('My Favorite Movie Is.' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(0, 100)
t.pendown()
t.write(': Saving Private Ryan.' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(0, -300)
t.pendown()
t.write('NEXT' ,font=('arial',30,"bold"),align="center")


round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor('red')

#screen5
t.penup()
t.goto(-100, -150)
t.pendown()
t.pencolor('pink')
t.fillcolor('pink')
t.begin_fill()
t.goto(0,0)
t.goto(100,-150)
t.goto(-100,-150)
t.end_fill()

t.penup()
t.goto(150,0)
t.pendown()
screen.addshape('TF.gif')
t.shape('TF.gif')
t.stamp()
t.shape('classic')

t.pencolor('Black')
t.penup()
t.goto(0, 300)
t.pendown()
t.write('My Favorite Sport Is.' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(0, 100)
t.pendown()
t.write(': Track and Field .' ,font=('arial',30,"bold"),align="center")

t.penup()
t.goto(0, -300)
t.pendown()
t.write('THE END' ,font=('arial',30,"bold"),align="center")








turtle.done()